_decks = {
	'corp':	[
		"Seidr Laboratories - TD Deck\n\nSeidr Laboratories: Destiny Defined\n\nAgenda (9)\n3x Accelerated Beta Test\n3x Elective Upgrade\n3x Successful Field Test\n\nAsset (8)\n3x Adonis Campaign\n1x Aggressive Secretary\n3x Marilyn Campaign\n1x Snare!  ●●\n\nUpgrade (4)\n1x Black Level Clearance\n2x Mason Bellamy\n1x SanSan City Grid  ★ ●●●\n\nOperation (10)\n2x Archived Memories\n2x Biotic Labor\n3x Hedge Fund\n3x IPO\n\nBarrier (5)\n2x Eli 2.0\n1x Heimdall 1.0\n2x Wall of Static\n\nCode Gate (8)\n1x Enigma\n1x Hortum  ●●\n2x Tapestry\n2x Tollbooth  ●●●●\n2x Viktor 1.0\n\nSentry (4)\n3x Ichi 1.0\n1x Rototurret\n\n12 influence spent (max 15, available 3)\n21 agenda points (between 20 and 21)\n48 cards (min 45)\nCards up to Terminal Directive\n\nDecklist published on https://netrunnerdb.com.",
		"Skorpius HS\n\nSkorpios Defense Systems: Persuasive Power\n\nAgenda (10)\n2x Armored Servers\n1x Graft\n3x Hostile Takeover\n1x Paper Trail\n3x Project Atlas\n\nAsset (5)\n2x Illegal Arms Factory\n3x Snare!  ●●●●● ●\n\nUpgrade (1)\n1x SanSan City Grid  ★ ●●●\n\nOperation (13)\n3x Beanstalk Royalties\n3x Hedge Fund\n3x Hunter Seeker\n1x IPO\n2x Scorched Earth\n1x SEA Source  ●●\n\nBarrier (5)\n1x Hailstorm\n3x Ice Wall\n1x Wall of Static\n\nCode Gate (5)\n2x Enigma\n3x Hortum\n\nSentry (5)\n2x Archer\n2x Bloodletter\n1x Colossus\n\n12 influence spent (max 15, available 3)\n18 agenda points (between 18 and 19)\n44 cards (min 40)\nCards up to Terminal Directive\n\nDeck built on https://netrunnerdb.com.",
		"Red Planet Takeover\n\nWeyland Consortium: Builder of Nations\n\nAgenda (6)\n1x Government Takeover\n2x High-Risk Investment\n3x Project Atlas\n\nAsset (5)\n3x Anson Rose\n2x Jackson Howard  ●●\n\nUpgrade (1)\n1x Bryan Stinson\n\nOperation (18)\n2x Biotic Labor  ●●●●● ●●●\n1x Closed Accounts  ●\n2x Dedication Ceremony\n3x Hedge Fund\n2x IPO\n3x Punitive Counterstrike\n2x Red Planet Couriers\n1x Restructure\n2x Shipment from Kaguya\n\nBarrier (5)\n1x Changeling\n3x Ice Wall\n1x Meru Mati\n\nCode Gate (5)\n2x Enigma\n2x Mausolus\n1x Wormhole\n\nSentry (4)\n2x Colossus\n1x Nebula\n1x Rototurret  ●\n\n12 influence spent (max 12, available 0)\n18 agenda points (between 18 and 19)\n44 cards (min 40)\nCards up to Terminal Directive\n\nDeck built on https://netrunnerdb.com.",
		"J Carter\n\nJemison Astronautics: Sacrifice. Audacity. Success.\n\nAgenda (11)\n2x Corporate Sales Team\n2x High-Risk Investment\n3x Hostile Takeover\n3x Project Atlas\n1x The Future is Now\n\nAsset (5)\n2x Corporate Town\n3x Jackson Howard  ●●●\n\nUpgrade (3)\n3x Oberth Protocol\n\nOperation (15)\n2x Dedication Ceremony\n2x Friends in High Places  ●●\n3x Hedge Fund\n2x IPO\n2x Paywall Implementation\n2x Sacrifice\n2x Trick of Light  ●●●●● ●\n\nBarrier (5)\n1x Changeling\n2x Ice Wall\n1x Meru Mati\n1x Spiderweb\n\nCode Gate (5)\n1x Enigma\n2x Lotus Field  ●●\n2x Mausolus\n\nSentry (5)\n1x Archer\n2x Sapper\n2x Veritas\n\n13 influence spent (max 15, available 2)\n20 agenda points (between 20 and 21)\n49 cards (min 45)\nCards up to Terminal Directive\n\nDeck built on https://netrunnerdb.com.",
		"Papercuts\n\nJinteki: Potential Unleashed\n\nAgenda (11)\n2x Braintrust\n3x Fetal AI\n2x House of Knives\n3x Medical Breakthrough\n1x Philotic Entanglement\n\nAsset (13)\n3x Bio-Ethics Association  ★★★\n2x Mental Health Clinic\n2x Project Junebug\n3x Shock!\n3x Synth DNA Modification\n\nUpgrade (5)\n2x Caprice Nisei\n2x Hokusai Grid\n1x Tori Hanzō\n\nOperation (8)\n2x Friends in High Places  ●●\n3x Hedge Fund\n3x Neural EMP\n\nBarrier (4)\n1x Chiyashi\n3x Kakugo\n\nCode Gate (2)\n2x DNA Tracker\n\nSentry (6)\n2x Bloodletter  ●●●●\n2x Neural Katana\n2x Swordsman\n\n9 influence spent (max 12, available 3)\n20 agenda points (between 20 and 21)\n49 cards (min 45)\nCards up to Terminal Directive\n\nDeck built on https://netrunnerdb.com."
	],
	'run':	[
		"Investigator Bios III\n\nAyla \"Bios\" Rahim: Simulant Specialist\n\nEvent (17)\n2x Careful Planning\n3x Diesel\n2x Modded\n3x Special Order  ●●●●● ●\n2x Sure Gamble\n2x The Maker's Eye\n3x Tinkering\n\nHardware (6)\n2x Akamatsu Mem Chip\n2x The Personal Touch\n2x Ubax\n\nResource (10)\n3x Councilman\n2x Dean Lister\n2x Decoy  ●●●●\n1x Ice Carver  ●●●\n2x Sacrificial Construct\n\nIcebreaker (10)\n2x Battering Ram\n1x Corroder  ●●\n2x Crypsis\n3x Gordian Blade\n2x Pipeline\n\nProgram (2)\n2x Magnum Opus\n\n15 influence spent (max 15, available 0)\n45 cards (min 45)\nCards up to Terminal Directive\n\nDeck built on https://netrunnerdb.com.",
		"Steve!\n\nSteve Cambridge: Master Grifter\n\nEvent (20)\n2x Account Siphon\n2x Brute-Force-Hack\n2x Diesel  ●●●●\n3x Easy Mark\n3x Inside Job\n3x Spear Phishing\n2x Special Order\n3x Sure Gamble\n\nHardware (1)\n1x Desperado\n\nResource (8)\n2x Bank Job\n2x Charlatan\n3x Councilman\n1x Data Dealer\n\nIcebreaker (11)\n3x Abagnale\n1x Corroder  ●●\n3x Demara\n3x Lustig\n1x Yog.0  ●\n\nProgram (5)\n2x Datasucker  ●●\n1x Medium  ●●●\n2x Sneakdoor Beta\n\n12 influence spent (max 15, available 3)\n45 cards (min 45)\nCards up to Terminal Directive\n\nDeck built on https://netrunnerdb.com.",
		"CT Litmus PreMWL\n\nChaos Theory: Wünderkind\n\nEvent (18)\n3x Diesel\n3x Legwork  &bull;&bull;&bull;&bull;&bull; &bull;\n1x Modded\n2x Quality Time\n3x Scavenge\n1x Stimhack  &bull;\n3x Test Run\n2x Vamp  &bull;&bull;&bull;&bull;\n\nHardware (8)\n2x Astrolabe\n3x Clone Chip\n3x R&D Interface\n\nIcebreaker (7)\n2x Cerberus \"Lady\" H1\n1x Femme Fatale  &bull;\n1x Mimic  &bull;\n1x Sharpshooter\n1x Torch\n1x ZU.13 Key Master\n\nProgram (7)\n1x Clot  &bull;&bull;\n3x Magnum Opus\n3x Self-modifying Code\n\n15 influence spent (max 15, available 0)\n40 cards (min 40)\nCards up to The Valley\n\nDeck built on https://netrunnerdb.com.",
		"Silhoueater\n\nSilhouette: Stealth Operative\n\nEvent (17)\n2x \"Freedom Through Equality\"\n3x Account Siphon\n3x Career Fair\n2x Mad Dash\n2x Notoriety  ●●\n2x Quest Completed  ●●●●\n3x Special Order\n\nHardware (4)\n3x Doppelgänger\n1x Unregistered S&W '35\n\nResource (14)\n3x Aaron Marrón\n2x Earthrise Hotel\n2x Kati Jones\n2x Political Operative\n2x Security Testing\n3x Temüjin Contract  ★★★\n\nIcebreaker (5)\n1x Abagnale\n1x Eater  ●●●\n1x Mammon\n1x Mongoose\n1x Paperclip  ●●●\n\n15 influence spent (max 15, available 0)\n40 cards (min 40)\nCards up to Terminal Directive\n\nDeck built on https://netrunnerdb.com.",
		"Hayley's Rig\n\nHayley Kaplan: Universal Scholar\n\nEvent (10)\n3x Diesel\n2x Indexing\n3x Sure Gamble\n2x Test Run\n\nHardware (15)\n3x Cybsoft MacroDrive\n1x HQ Interface  ●●\n3x LLDS Processor\n1x Plascrete Carapace\n2x R&D Interface\n3x Replicator\n2x The Toolbox\n\nResource (11)\n3x Inside Man\n2x Sacrificial Construct\n3x Technical Writer\n3x Temüjin Contract  ★★★ ●●●●● ●\n\nIcebreaker (6)\n3x Chameleon\n1x Garrote  ●●●\n1x Gordian Blade\n1x Snowball\n\nProgram (3)\n3x Magnum Opus\n\n14 influence spent (max 15, available 1)\n45 cards (min 45)\nCards up to Blood Money\n\nDeck built on https://netrunnerdb.com.",
		"Andysucker\n\nAndromeda: Dispossessed Ristie\n\nEvent (17)\n1x Account Siphon  ●●●●\n3x Careful Planning\n3x Deep Data Mining\n3x Diesel\n2x Modded\n2x Special Order  ●●●●\n3x Sure Gamble\n\nHardware (5)\n2x Akamatsu Mem Chip\n3x Ubax\n\nResource (9)\n3x Armitage Codebusting\n3x Dean Lister\n2x Sacrificial Construct\n1x The Shadow Net\n\nIcebreaker (7)\n2x Adept\n1x Corroder  ●●\n1x Gordian Blade\n1x Mimic  ●\n2x Savant\n\nProgram (7)\n2x Datasucker  ●●\n3x Dhegdheer\n2x Magnum Opus\n\n13 influence spent (max 15, available 2)\n45 cards (min 45)\nCards up to Terminal Directive\n\nDeck built on https://netrunnerdb.com.",
		"Maxx Retrieval\n\nMaxX: Maximum Punk Rock\n\nEvent (16)\n3x Day Job\n3x Déjà Vu\n1x Levy AR Lab Access  ●●●\n3x Retrieval Run\n3x Stimhack\n3x Sure Gamble\n\nHardware (8)\n2x Clone Chip  ★★ ●●●●\n3x Cyberfeeder\n3x Grimoire\n\nResource (6)\n3x Armitage Codebusting\n3x Same Old Thing\n\nIcebreaker (8)\n3x Corroder\n3x Mimic\n2x Yog.0  ★★\n\nProgram (7)\n3x Datasucker\n1x Medium\n3x Parasite  ★★★\n\n7 influence spent (max 15-7★=8, available 1)\n45 cards (min 45)\nCards up to Order and Chaos\n\nDeck built on https://netrunnerdb.com."
	]
};