_roles = [{
	"id": 1,
	"rolename": "Street Samurai",
	"rolecode": "S",
	"rolecolour":	"000000",
	"startdeck": [13, 13 ,13 ,13 ,1 ,5 ,9]
}, {
	"id": 2,
	"rolename": "Mage",
	"rolecode": "M",
	"rolecolour":	"333399",
	"startdeck": [5, 5, 5, 5, 1, 9, 13]
}, {
	"id": 3,
	"rolename": "Decker",
	"rolecode": "D",
	"rolecolour":	"006600",
	"startdeck": [1, 1, 1, 1, 5, 9, 13]
}, {
	"id": 4,
	"rolename": "Face",
	"rolecode": "F",
	"rolecolour":	"cc0000",
	"startdeck": [9, 9, 9, 9, 1, 5, 13]
}];

_metas = [{
	"id": 1,
	"meta": "Elf",
	"gender": "F",
	"starthits": 4,
	"startcards": 4,
	"startnuyen": 4
}, {
	"id": 2,
	"meta": "Human",
	"gender": "M",
	"starthits": 5,
	"startcards": 4,
	"startnuyen": 3
}, {
	"id": 3,
	"meta": "Troll",
	"gender": "F",
	"starthits": 7,
	"startcards": 3,
	"startnuyen": 2
}, {
	"id": 4,
	"meta": "Ork",
	"gender": "M",
	"starthits": 6,
	"startcards": 5,
	"startnuyen": 1
}];

_obstacles = [{
	"id": 1,
	"name": "Out of Ammo",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Tech",
	"nuyen": 4,
	"attack": 1,
	"track": ["W", "3"],
	"ability": "You can't play more than 2 cards on your turn."
}, {
	"id": 2,
	"name": "Corporate Adept",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "Human",
	"nuyen": 4,
	"attack": 1,
	"track": ["M", "3"],
	"ability": "You can't be healed or heal any runner."
}, {
	"id": 3,
	"name": "Ork Fixer",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "Ork",
	"nuyen": 4,
	"attack": 1,
	"track": ["S", "3"],
	"ability": "You can't buy cards."
}, {
	"id": 4,
	"name": "Deckhead",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Human",
	"nuyen": 4,
	"attack": 1,
	"track": ["2", "H", "1", "W"],
	"ability": ""
}, {
	"id": 5,
	"name": "Astral Shiver",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "6th World",
	"nuyen": 4,
	"attack": 1,
	"track": ["3", "M", "M"],
	"ability": ""
}, {
	"id": 6,
	"name": "Sudden Fade",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Tech",
	"nuyen": 4,
	"attack": 1,
	"track": ["3", "H", "H"],
	"ability": ""
}, {
	"id": 7,
	"name": "Eye Alarm",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "6th World",
	"nuyen": 4,
	"attack": 1,
	"track": ["2", "S", "1", "M"],
	"ability": ""
}, {
	"id": 8,
	"name": "Ancients Ganger",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Elf",
	"nuyen": 5,
	"attack": 2,
	"track": ["M", "3", "W"],
	"ability": ""
}, {
	"id": 9,
	"name": "Fire Adept",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "Human",
	"nuyen": 5,
	"attack": 2,
	"track": ["3", "M", "W"],
	"ability": ""
}, {
	"id": 10,
	"name": "Trip Beams",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Tech",
	"nuyen": 5,
	"attack": 2,
	"track": ["S", "3", "H"],
	"ability": ""
}, {
	"id": 11,
	"name": "Gutter Punks",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Human",
	"nuyen": 5,
	"attack": 1,
	"track": ["2", "W", "3"],
	"ability": "DEFEATED: Choose a runner. That runner heals 1 HP."
}, {
	"id": 12,
	"name": "Wage Mage",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "Human",
	"nuyen": 5,
	"attack": 1,
	"track": ["3", "M", "2"],
	"ability": "FLIPPED: You can cycle 1 non-SPELL card in the Black Market."
}, {
	"id": 13,
	"name": "Customs Officer",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "Human",
	"nuyen": 5,
	"attack": 1,
	"track": ["3", "S", "2"],
	"ability": "DEFEATED: Chose another runner. That runner draws 1 card."
}, {
	"id": 14,
	"name": "Elf Shaman",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "Elf",
	"nuyen": 6,
	"attack": 1,
	"track": ["2", "2", "S", "2", "M"],
	"ability": "When THIS attacks, it heals 1 level."
}, {
	"id": 15,
	"name": "Light Combat Drone",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Tech",
	"nuyen": 6,
	"attack": 1,
	"track": ["4", "H", "1", "W", "1"],
	"ability": "FLIPPED: You discard 1 card."
}, {
	"id": 16,
	"name": "Demolittions Expert",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "Human",
	"nuyen": 8,
	"attack": 2,
	"track": ["3", "2", "S", "2", "W"],
	"ability": "DEFEATED: Deal 1 level of damage to another obstacle."
}, {
	"id": 17,
	"name": "Aerial Combat Drone",
	"democount": 1,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Tech",
	"nuyen": 8,
	"attack": 2,
	"track": ["2", "H", "1", "W", "1", "H", "1", "S"],
	"ability": "DEFEATED: Choose another runner. That runner draws 1 card, then discards 1 card."
}, {
	"id": 18,
	"name": "Buzzback",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Tech",
	"nuyen": 4,
	"attack": 1,
	"track": ["H", "6"],
	"ability": "You can’t draw cards."
}, {
	"id": 19,
	"name": "Yak Muscle",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Human",
	"nuyen": 5,
	"attack": 2,
	"track": ["3", "W", "H"],
	"ability": ""
}, {
	"id": 20,
	"name": "Ancients Sentry",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "Elf",
	"nuyen": 5,
	"attack": 2,
	"track": ["M", "3", "S"],
	"ability": ""
}, {
	"id": 21,
	"name": "Chipped Decker",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Human",
	"nuyen": 5,
	"attack": 1,
	"track": ["2", "H", "3"],
	"ability": "FLIPPED: You can cycle 1 non-HACKING card in the Black Market."
}, {
	"id": 22,
	"name": "Lone Star Trooper",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Human",
	"nuyen": 6,
	"attack": 1,
	"track": ["5", "H", "W"],
	"ability": "When THIS attacks it also attacks the Street Samurai unless it’s already facing that runner."
}, {
	"id": 23,
	"name": "Freelance Assassin",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Ork",
	"nuyen": 6,
	"attack": 1,
	"track": ["3", "W", "W", "1", "H"],
	"ability": "After THIS attacks, discard the top card of the Black Market deck. Move THIS to face the matching coloured runner."
}, {
	"id": 24,
	"name": "Spirit of Air",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "6th World",
	"nuyen": 6,
	"attack": 1,
	"track": ["5", "M", "M"],
	"ability": "When THIS attacks it also attacks the Mage unless it’s already facing that runner."
}, {
	"id": 25,
	"name": "Aztlan Decker",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Human",
	"nuyen": 6,
	"attack": 1,
	"track": ["3", "S", "2", "H"],
	"ability": "When THIS attacks it also attacks the Decker unless it’s already facing that runner."
}, {
	"id": 26,
	"name": "Jaguar Shifter",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "6th World",
	"nuyen": 6,
	"attack": 1,
	"track": ["2", "S", "2", "M", "S"],
	"ability": "When THIS attacks it also attacks the Face unless it’s already facing that runner."
}, {
	"id": 27,
	"name": "Wired Merc",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Dwarf",
	"nuyen": 11,
	"attack": 2,
	"track": ["4", "H", "3", "W", "2", "H"],
	"ability": "FLIPPED (2+): Each non-Dwarf runner facing a Green obstacle discards 2 cards."
}, {
	"id": 28,
	"name": "Bonelaced Adept",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "Troll",
	"nuyen": 6,
	"attack": 2,
	"track": ["4", "M", "1", "W"],
	"ability": "FLIPPED: Cycle all SPELL and WEAPON cards in the Black Market Deck."
}, {
	"id": 29,
	"name": "Spell Sniper",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "Human",
	"nuyen": 5,
	"attack": 1,
	"track": ["1", "M", "4", "M"],
	"ability": "FLIPPED: Each runner places 2 cards from the top of their deck into their discard."
}, {
	"id": 30,
	"name": "Combat Decker",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Human",
	"nuyen": 5,
	"attack": 1,
	"track": ["1", "S", "3", "W", "H"],
	"ability": "FLIPPED: Cycle the card in the Black Market that has the lowest cost."
}, {
	"id": 31,
	"name": "Gang Leader",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "Ork",
	"nuyen": 5,
	"attack": 1,
	"track": ["S", "5", "S"],
	"ability": "FLIPPED: Each runner places 4 cards from the top of their deck into their discard."
}, {
	"id": 32,
	"name": "Troll Enforcer",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Troll",
	"nuyen": 6,
	"attack": 2,
	"track": ["2", "W", "2", "2", "M"],
	"ability": ""
}, {
	"id": 33,
	"name": "Covert Ops Specialist",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "Human",
	"nuyen": 6,
	"attack": 1,
	"track": ["3", "3", "S", "S"],
	"ability": "FLIPPED: Choose a runner. That runner takes 1 damage."
}, {
	"id": 34,
	"name": "Security Goons",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Human",
	"nuyen": 8,
	"attack": 2,
	"track": ["3", "2", "H", "2", "W"],
	"ability": "FLIPPED: Cycle 1 non-WEAPON card in the Black Market. DEFEATED: Choose a runner. That runner heals 1 HP."
}, {
	"id": 35,
	"name": "Astral Scout",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "6th World",
	"nuyen": 8,
	"attack": 2,
	"track": ["1", "2", "3", "M", "1", "M"],
	"ability": "DEFEATED: Look at the top Crossfire card and replace it either on top or on bottom."
}, {
	"id": 36,
	"name": "Courier",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "Human",
	"nuyen": 8,
	"attack": 2,
	"track": ["2", "S", "2", "2", "H", "S"],
	"ability": "FLIPPED: The next runner who buys a card from the Black Market can pay 1 less Nuyen for that card."
}, {
	"id": 37,
	"name": "Ork Bounty Hunter",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "W",
	"type": "Ork",
	"nuyen": 11,
	"attack": 2,
	"track": ["3", "H", "3", "W", "W", "3"],
	"ability": "FLIPPED (2+): Each non-Ork runner facing a Black obstacle discards 2 cards."
}, {
	"id": 38,
	"name": "Troll Mage",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "M",
	"type": "Troll",
	"nuyen": 11,
	"attack": 2,
	"track": ["3", "W", "3", "M", "2", "2"],
	"ability": "FLIPPED (2+): Each non-Troll runner facing a Blue obstacle discards 2 cards."
}, {
	"id": 39,
	"name": "Mercenary Elf Decker",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "H",
	"type": "Elf",
	"nuyen": 6,
	"attack": 2,
	"track": ["2", "H", "1", "S", "2"],
	"ability": "FLIPPED: Cycle all HACKING and SKILL cards in the Black Market Deck."
}, {
	"id": 40,
	"name": "Scrybot Tracer",
	"democount": 0,
	"corecount": 1,
	"level": 1,
	"role": "S",
	"type": "Tech",
	"nuyen": 11,
	"attack": 2,
	"track": ["5", "M", "5", "S"],
	"ability": "FLIPPED (2+): Each runner facing a Red obstacle discards 2 cards."
}, {
	"id": 41,
	"name": "Lightning Mage",
	"democount": 1,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "Human",
	"nuyen": 3,
	"attack": 1,
	"track": ["3", "M", "M", "1"],
	"ability": "Runners can’t be healed."
}, {
	"id": 42,
	"name": "Knight Errant Field Agent",
	"democount": 1,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "Dwarf",
	"nuyen": 3,
	"attack": 2,
	"track": ["4", "H", "3", "S"],
	"ability": ""
}, {
	"id": 43,
	"name": "Armored Troopers",
	"democount": 1,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "Human",
	"nuyen": 4,
	"attack": 2,
	"track": ["4", "W", "2", "S", "2", "W"],
	"ability": "DEFEATED: Choose a runner. That runner heals 2 HP."
}, {
	"id": 44,
	"name": "Spirit of Fire",
	"democount": 1,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "6th World",
	"nuyen": 4,
	"attack": 2,
	"track": ["3", "4", "W", "2", "M"],
	"ability": "FLIPPED: Deal 1 level of damage to another obstacle."
}, {
	"id": 45,
	"name": "Warded Decker",
	"democount": 1,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Human",
	"nuyen": 4,
	"attack": 2,
	"track": ["2", "M", "S", "3", "3", "H"],
	"ability": "FLIPPED: You draw 2 cards, then discard 1 card."
}, {
	"id": 46,
	"name": "Chromed Samurai",
	"democount": 1,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "Human",
	"nuyen": 5,
	"attack": 2,
	"track": ["4", "H", "W", "2", "M", "2", "W"],
	"ability": ""
}, {
	"id": 47,
	"name": "Drone Rigger",
	"democount": 1,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Human",
	"nuyen": 5,
	"attack": 2,
	"track": ["5", "W", "1", "H", "3", "H"],
	"ability": ""
}, {
	"id": 48,
	"name": "Security Chief",
	"democount": 1,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "Human",
	"nuyen": 5,
	"attack": 2,
	"track": ["4", "S", "W", "3", "S", "2"],
	"ability": ""
}, {
	"id": 49,
	"name": "Drake Enforcer",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "6th World",
	"nuyen": 2,
	"attack": 1,
	"track": ["H", "W", "M", "S"],
	"ability": "When THIS attacks discard the top card of the Black Market deck. Each runner discards 1 matching colour card."
}, {
	"id": 50,
	"name": "Lone Star Sergeant",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "Human",
	"nuyen": 3,
	"attack": 1,
	"track": ["2", "W", "2", "W"],
	"ability": "Runners can't buy cards."
}, {
	"id": 51,
	"name": "IC",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Tech",
	"nuyen": 3,
	"attack": 1,
	"track": ["3", "H", "H", "H"],
	"ability": "When THIS attacks, each runner discards 1 card."
}, {
	"id": 52,
	"name": "Trickster Initiate",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "Human",
	"nuyen": 3,
	"attack": 1,
	"track": ["1", "M", "S", "3"],
	"ability": "Obstacles ignore colorless damage applied to them."
}, {
	"id": 53,
	"name": "Drake Assassin",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "6th World",
	"nuyen": 4,
	"attack": 1,
	"track": ["H", "W", "M", "S", "H", "W", "M", "S"],
	"ability": "When THIS attacks, discard the top card of the Black Market deck. Each runner discards matching cost."
}, {
	"id": 54,
	"name": "Border War Vet",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "Ork",
	"nuyen": 3,
	"attack": 2,
	"track": ["4", "M", "W", "W", "2"],
	"ability": ""
}, {
	"id": 55,
	"name": "Mage Hunter",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "Elf",
	"nuyen": 3,
	"attack": 2,
	"track": ["2", "2", "S", "3", "M"],
	"ability": ""
}, {
	"id": 56,
	"name": "Indentured Otaku",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Human",
	"nuyen": 3,
	"attack": 2,
	"track": ["5", "H", "1", "H"],
	"ability": ""
}, {
	"id": 57,
	"name": "Lone Start Lieutenant",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "Human",
	"nuyen": 4,
	"attack": 2,
	"track": ["3", "H", "5", "W"],
	"ability": "You can’t buy cards. Any runner can discard a WEAPON to cancel until next turn."
}, {
	"id": 58,
	"name": "Spirit of Earth",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "6th World",
	"nuyen": 4,
	"attack": 2,
	"track": ["1", "2", "3", "S", "2", "M"],
	"ability": "You can't play cards. Any runner can discard a SPELL to cancel until next turn."
}, {
	"id": 59,
	"name": "Military Spec IC",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Tech",
	"nuyen": 4,
	"attack": 2,
	"track": ["3", "S", "4", "H", "1"],
	"ability": "You don’t receive Nuyen (discarded). Any runner can discard a HACKING to cancel until next turn."
}, {
	"id": 60,
	"name": "Ares Field Rep",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "Human",
	"nuyen": 4,
	"attack": 2,
	"track": ["4", "4", "S", "S"],
	"ability": "You can’t draw cards. Any runner can discard a SKILL to cancel until next turn."
}, {
	"id": 61,
	"name": "Tir Ghost",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "Elf",
	"nuyen": 4,
	"attack": 2,
	"track": ["S", "5", "M", "2", "W"],
	"ability": "FLIPPED: Each non-Elf runner discards their hand, then draws that number of cards."
}, {
	"id": 62,
	"name": "Renraku Red Samurai",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "Human",
	"nuyen": 4,
	"attack": 2,
	"track": ["7", "S", "W", "S"],
	"ability": "FLIPPED: Each non-Human runner discards their hand, then draws that number of cards."
}, {
	"id": 63,
	"name": "Bug Spirit",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "6th World",
	"nuyen": 3,
	"attack": 1,
	"track": ["1", "M", "6", "W", "M"],
	"ability": "FLIPPED: Each runner discards their hand, then draws that number of cards."
}, {
	"id": 64,
	"name": "Guy in the Van",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Dwarf",
	"nuyen": 3,
	"attack": 1,
	"track": ["6", "H", "H", "1", "W"],
	"ability": "FLIPPED: The runner with the most HP draws 2 cards and takes 2 damage."
}, {
	"id": 65,
	"name": "Grey Ops Riggers Team",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Tech",
	"nuyen": 3,
	"attack": 1,
	"track": ["3", "H", "2", "M", "1", "S", "H"],
	"ability": "FLIPPED: Cycle all cards in the Black Market."
}, {
	"id": 66,
	"name": "Unusual Suspects",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "6th World",
	"nuyen": 4,
	"attack": 2,
	"track": ["4", "M", "2", "H", "1", "H", "S"],
	"ability": "DEFEATED: Choose 2 different runners. One runner heals 1 HP, the other draws 1 card."
}, {
	"id": 67,
	"name": "Weapons Specialist",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "Human",
	"nuyen": 5,
	"attack": 1,
	"track": ["6", "S", "3", "W"],
	"ability": "At the start of your turn all runners facing Black take 1 damage. Any runner can discard WEAPON to cancel until next turn."
}, {
	"id": 68,
	"name": "Corporate Shaman",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "Dwarf",
	"nuyen": 5,
	"attack": 1,
	"track": ["4", "1", "H", "4", "M"],
	"ability": "At the start of your turn each Blue obstacle heals 1 level. Any runner can discard a SPELL to cancel until next turn."
}, {
	"id": 69,
	"name": "Banshee Virus",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Tech",
	"nuyen": 5,
	"attack": 1,
	"track": ["5", "4", "H", "H"],
	"ability": "At the start of your turn pay 1 for each Green you face. Any runner can discard a HACKING to cancel until next turn."
}, {
	"id": 70,
	"name": "Saeder-Krupp Observer",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "Human",
	"nuyen": 5,
	"attack": 1,
	"track": ["3", "S", "3", "W", "2", "S"],
	"ability": "At the start of your turn each RED obstacle heals 1 level. Any runner can discard a SKILL to cancel until next turn."
}, {
	"id": 71,
	"name": "Gunslinger Adept",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "Ork",
	"nuyen": 5,
	"attack": 1,
	"track": ["6", "M", "W", "2", "M"],
	"ability": "Damage can’t be applied to THIS. Any runner can discard a WEAPON or SPELL to cancel until next turn."
}, {
	"id": 72,
	"name": "Fomorian Mage",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "Troll",
	"nuyen": 5,
	"attack": 2,
	"track": ["5", "S", "M", "3", "W", "M"],
	"ability": ""
}, {
	"id": 73,
	"name": "Gargoyle",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "6th World",
	"nuyen": 6,
	"attack": 2,
	"track": ["6", "6", "W", "W"],
	"ability": "DEFEATED: Choose a runner. That runner takes 1 damage."
}, {
	"id": 74,
	"name": "Elf Blademaster",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "W",
	"type": "Elf",
	"nuyen": 6,
	"attack": 2,
	"track": ["6", "S", "H", "M", "3", "W", "H"],
	"ability": "FLIPPED (3+): Between them, the team discards cards equal to the number of runners."
}, {
	"id": 75,
	"name": "Combat Shaman",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "Human",
	"nuyen": 6,
	"attack": 2,
	"track": ["4", "H", "M", "6", "M", "M"],
	"ability": "(3+): When THIS attacks each obstacle heals 1 level."
}, {
	"id": 76,
	"name": "Mercenary Technomancer",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "M",
	"type": "Ork",
	"nuyen": 6,
	"attack": 2,
	"track": ["3", "M", "M", "5", "W", "W", "2"],
	"ability": "FLIPPED: The runner with the most cards in their hand discards 1 card."
}, {
	"id": 77,
	"name": "Chaos Sprite",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Tech",
	"nuyen": 6,
	"attack": 2,
	"track": ["4", "M", "S", "H", "4", "3"],
	"ability": "FLIPPED (2+): Each runner discards their hand then draws that number of cards minus one."
}, {
	"id": 78,
	"name": "GODwire",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "H",
	"type": "Tech",
	"nuyen": 6,
	"attack": 2,
	"track": ["8", "W", "S", "2", "H", "H"],
	"ability": "When this attacks it heals 2 levels."
}, {
	"id": 79,
	"name": "Aztlan Veteran",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "Human",
	"nuyen": 6,
	"attack": 2,
	"track": ["5", "S", "5", "W", "1", "S"],
	"ability": "FLIPPED: The runner with the most HP takes 1 damage."
}, {
	"id": 80,
	"name": "Vampire Operative",
	"democount": 0,
	"corecount": 1,
	"level": 2,
	"role": "S",
	"type": "6th World",
	"nuyen": 6,
	"attack": 2,
	"track": ["2", "S", "6", "M", "S", "3"],
	"ability": "(3+): When THIS attacks it also deals 1 damage to each runner."
}]

_blackmarket = [
{
	"id": 1,
	"role": "H",
	"basic": 1,
	"type": "Hacking",
	"name": "Mark",
	"count": 8,
	"cost": 0,
	"damage": ["H"],
	"notes": ""
}, {
	"id": 2,
	"role": "H",
	"basic": 0,
	"type": "Hacking",
	"name": "Jacked In",
	"count": 4,
	"cost": 3,
	"damage": ["H", "1"],
	"notes": "Discard one card to return Jacked In from discard"
}, {
	"id": 3,
	"role": "H",
	"basic": 0,
	"type": "Hacking",
	"name": "Icon Grab",
	"count": 4,
	"cost": 2,
	"damage": ["H", "*"],
	"notes": "* = If you played another HACKING card + B, L, or R damage"
}, {
	"id": 4,
	"role": "H",
	"basic": 0,
	"type": "Hacking",
	"name": "Retrieval Agent",
	"count": 2,
	"cost": 4,
	"damage": ["H", "1"],
	"notes": "Return a HACKING card from discard"
}, {
	"id": 5,
	"role": "M",
	"basic": 1,
	"type": "Spell",
	"name": "Mana",
	"count": 8,
	"cost": 0,
	"damage": ["M"],
	"notes": ""
}, {
	"id": 6,
	"role": "M",
	"basic": 0,
	"type": "Spell",
	"name": "Clairvoyance",
	"count": 3,
	"cost": 2,
	"damage": ["M"],
	"notes": "Draw 1, discard 1 - ASSIST: Draw 1, discard 1, & L Damage"
}, {
	"id": 7,
	"role": "M",
	"basic": 0,
	"type": "Spell",
	"name": "Deathtouch",
	"count": 4,
	"cost": 4,
	"damage": ["L", "L", "X"],
	"notes": "Reveal and replace top 3 cards in choice order: X = # SPELL cards"
}, {
	"id": 8,
	"role": "M",
	"basic": 0,
	"type": "Spell",
	"name": "Lightning Bolt",
	"count": 2,
	"cost": 6,
	"damage": ["*"],
	"notes": "* = Deal two levels of damage - Requires SPELL to Buy"
}, {
	"id": 9,
	"role": "F",
	"basic": 1,
	"type": "Skill",
	"name": "Street Smarts",
	"count": 8,
	"cost": 0,
	"damage": ["F"],
	"notes": ""
}, {
	"id": 10,
	"role": "F",
	"basic": 0,
	"type": "Skill",
	"name": "Negotiation",
	"count": 3,
	"cost": 3,
	"damage": ["F"],
	"notes": "Next SKILL card purchase cost -1¥ for each SKILL card played - ASSIST: Current runner pays -1¥ less on next buy + R1 Damage"
}, {
	"id": 11,
	"role": "F",
	"basic": 0,
	"type": "Skill",
	"name": "Coordinated Attack",
	"count": 3,
	"cost": 4,
	"damage": ["F", "1"],
	"notes": "Another runner draws 1 card and plays 1 card"
}, {
	"id": 12,
	"role": "F",
	"basic": 0,
	"type": "Skill",
	"name": "Doc Wagon Contract",
	"count": 3,
	"cost": 5,
	"damage": [],
	"notes": "Heal 2 anyone - ASSIST: Heal 1 and do R damage"
}, {
	"id": 13,
	"role": "S",
	"basic": 1,
	"type": "Weapon",
	"name": "Quick Shot",
	"count": 8,
	"cost": 0,
	"damage": ["S"],
	"notes": ""
}, {
	"id": 14,
	"role": "S",
	"basic": 0,
	"type": "Weapon",
	"name": "Monofilament Whip",
	"count": 3,
	"cost": 2,
	"damage": ["S"],
	"notes": "Move obstacle to you, which can't attack if you played another WEAPON card this turn"
}, {
	"id": 15,
	"role": "S",
	"basic": 0,
	"type": "Weapon",
	"name": "Katana",
	"count": 3,
	"cost": 4,
	"damage": ["S", "S"],
	"notes": "Other WEAPON cards get + 1 damage"
}


];
/*
, {
	"id": 6,
	"role": "S",
	"basic": 0,
	"type": "Weapon",
	"name": "Remington Roomsweeper",
	"count": 3,
	"cost": 3,
	"damage": ["S", "1", "*"],
	"notes": "* = Deal this damage to all obstacles facing 1 runner"
}, {
	"id": 8,
	"role": "S",
	"basic": 0,
	"type": "Weapon",
	"name": "RA SM-4 Sniper Rifle",
	"count": 2,
	"cost": 4,
	"damage": ["*"],
	"notes": "* = Deal last two levels of damage"
}, {
	"id": 9,
	"role": "S",
	"basic": 0,
	"type": "Weapon",
	"name": "Covering Fire",
	"count": 3,
	"cost": 5,
	"damage": ["S", "1"],
	"notes": "Heal other runner 1 - ASSIST: Obstacle can't attack & B damage"
}, {
	"id": 10,
	"role": "S",
	"basic": 0,
	"type": "Weapon",
	"name": "Aztechnology Striker",
	"count": 1,
	"cost": 9,
	"damage": ["S", "S", "2"],
	"notes": "Move # of obstacles equal to runner count in front of youObstacles can't attack this turn"
}, {
	"id": 12,
	"role": "M",
	"basic": 0,
	"type": "Spell",
	"name": "Guiding Spirit",
	"count": 3,
	"cost": 3,
	"damage": ["M", "1"],
	"notes": "Discard and replace hand - Requires SPELL to Buy"
}, {
	"id": 13,
	"role": "M",
	"basic": 0,
	"type": "Spell",
	"name": "Stunbolt",
	"count": 2,
	"cost": 3,
	"damage": ["L", "X"],
	"notes": "Reveal and replace top card on deck: X Damage = Cost of reveal"
}, {
	"id": 16,
	"role": "M",
	"basic": 0,
	"type": "Spell",
	"name": "Fireball",
	"count": 1,
	"cost": 9,
	"damage": ["L", "L", "2", "*"],
	"notes": "* = Deal 1 level of damage to 3 different obstacles"
}, {
	"id": 19,
	"role": "H",
	"basic": 0,
	"type": "Hacking",
	"name": "Backdoor",
	"count": 2,
	"cost": 4,
	"damage": ["H", "2"],
	"notes": "ASSIST: Cancel obstacle abilities + G damage"
}, {
	"id": 21,
	"role": "H",
	"basic": 0,
	"type": "Hacking",
	"name": "Pair Programming",
	"count": 2,
	"cost": 5,
	"damage": ["H", "H"],
	"notes": "Play card worth up to 3¥ from other runner's discard, or discard a HACKING card to play other's discarded card of any cost"
}, {
	"id": 22,
	"role": "H",
	"basic": 0,
	"type": "Hacking",
	"name": "Hack the World",
	"count": 1,
	"cost": 9,
	"damage": ["H", "H", "2"],
	"notes": "Play Black Market card of 6¥ or less and discard to Black Market"
}, {
	"id": 23,
	"role": "F",
	"basic": 0,
	"type": "Skill",
	"name": "Black Market Contacts",
	"count": 3,
	"cost": 2,
	"damage": ["F"],
	"notes": "Buy a card from Black Market into hand during Play Cards phase"
}, {
	"id": 27,
	"role": "F",
	"basic": 0,
	"type": "Skill",
	"name": "Press the Advantage",
	"count": 2,
	"cost": 5,
	"damage": ["F"],
	"notes": "Draw cards until duplicate color. Discard last dup, keep rest."
}, {
	"id": 28,
	"role": "F",
	"basic": 0,
	"type": "Skill",
	"name": "Hero Move",
	"count": 1,
	"cost": 9,
	"damage": ["F", "F", "2"],
	"notes": "Each runner draws a card"
}
*/

_crossfire = [{
	"id": 1,
	"name": "Take the Merchandise and Run",
	"continuous": "Each runner with 5 HP or more takes 2 damage and places the top card of the Black Market deck into their hand.",
	"timebomb": "When this card is placed in the discard, each runner takes 1 damage.",
	"crossfirelevel": "",
	"crossfire": "",
	"flavour": "We thought we'd be smart and pick up Ares' new sniper rifle on the black market as soon as it showed up. So did everybody else. Adrenaline hit me so hard, I swear I outran a few bullets."
}, {
	"id": 2,
	"name": "Timebomb",
	"continuous": "",
	"timebomb": "When this card is placed in the discard, each runner takes 1 damage.",
	"crossfirelevel": 8,
	"crossfire": "Instead of taking 1 damage, each runner takes 3 damage.",
	"flavour": "You wanna know how I lost my hand? I’ll tell you how I lost my hand. What kind of asshole sets his bomb in metric time?"
}, {
	"id": 3,
	"name": "Instinct",
	"continuous": "The current runner takes 1 damage at the end of their turn if they played cards of more than one color that turn.",
	"timebomb": "",
	"crossfirelevel": 4,
	"crossfire": "Instead of 1 damage, the current runner takes 2 damage.",
	"flavour": "The middle of a shootout isn’t the right time to mess around with new toys. Stick to what you know."
}, {
	"id": 4,
	"name": "No Holding Back",
	"continuous": "Each turn, immediately before the Draw & Buy step, the current runner takes 1 damage for each card in their hand.",
	"timebomb": "",
	"crossfirelevel": "",
	"crossfire": "",
	"flavour": "My opinion is, you don’t go in guns blazing, you don’t deserve to survive the fight. What are you waiting for?"
}, {
	"id": 5,
	"name": "Win One, Lose One",
	"continuous": "At the start of each turn, the current runner gains 1[nuyen] and discards 1 card.",
	"timebomb": "",
	"crossfirelevel": "",
	"crossfire": "",
	"flavour": "We were sent to retrieve one commlink, but the body we found had two. We took both—never hurts to have something you can sell for quick cash."
}, {
	"id": 6,
	"name": "Chummers",
	"continuous": "The Attack Strength of each Human obstacle is increased by +1.",
	"timebomb": "",
	"crossfirelevel": 5,
	"crossfire": "In addition, reveal cards from the Normal Obstacle deck until you reveal a Human obstacle and place it facing the runner whose role color matches it. Discard the rest.",
	"flavour": "I don’t know how that ugly, lying, back-stabbing, thick-headed son-ofa-bitch made any friends. I guess even the lousiest bastard has some chummers that will stand up for him in a fight."
}, {
	"id": 7,
	"name": "Enemy Comms",
	"continuous": "The Attack Strength of each Green obstacle and Red obstacle is increased by +1.",
	"timebomb": "",
	"crossfirelevel": 4,
	"crossfire": "In addition, each Green obstacle and Red obstacle heals all levels.",
	"flavour": "When we pinned two guards by the chemical tank and a few others approached and lobbed smoke grenades right into our position, we learned we hadn’t jammed their communications as well as we thought."
}, {
	"id": 8,
	"name": "Unfriendly Fire",
	"continuous": "The Attack Strength of each Black obstacle and Blue obstacle is increased by +1.",
	"timebomb": "",
	"crossfirelevel": 4,
	"crossfire": "In addition, each Black obstacle and Blue obstacle heals all levels.",
	"flavour": "I don’t know what the hell just happened! It’s like their guns drew guns of their own!"
}]

